### ISSUE TITLE
LARAVEL 5.4 issue on the provider 

### ISSUE THREAD

**Issue by mourareaupro** [restoore/systempay-webservice#1]
Hello , I tried to install the package but i get Symfony\Component\Debug\Exception\FatalErrorException]                                           
  Class 'Restoore\SystempayWebserviceServiceProvider\SystempayWebserviceServiceProvider' not found 

When i enter the service provider i get a reflextionException ! could you update this ? thanks a lot in advance

**Comment by restoore** [comment]
hello,

i've found the issue, you have to change the class path in your
config/app.php file :

   - change Restoore\SystempayWebserviceServiceProvider\
   SystempayWebserviceServiceProvider to Restoore\
   *SystempayWebserviceService*\SystempayWebserviceServiceProvider

i've updated the documentation today.
Thanks for your help!

Florian


2017-06-19 18:05 GMT+02:00 mourareaupro <notifications@github.com>:

**Comment by mourareaupro** [comment]
thanks for your reply ! are you sure it's Restoore\**SystempayWebserviceService**\SystempayWebserviceServiceProvider,? i get a red line on this when i try to put it in my service providers

**Comment by mourareaupro** [comment]
thanks for your reply but i get : PHP Fatal error:  Undefined constant 'Restoore\SystempayWebserviceService\SystempayWebserviceServiceProvider'

**Comment by restoore** [comment]
dont forget to launch : composer update 

`'providers' => [
                   Restoore\SystempayWebservice\SystempayWebserviceServiceProvider::class
]  
`

`'aliases' => [
                        'SystempayWebservice' => Restoore\SystempayWebservice\Facades\SystempayWebservice::class 
] `

**Comment by mourareaupro** [comment]
now it's work !!! thanks a lot !
