### ISSUE TITLE
Code uncoupling

### ISSUE THREAD

**Issue by Cethy** [restoore/systempay-webservice#3]
Thank you for this work, you're saving my butt (damn old as f* api & documentation ...).
But I'm using symfony (4.0), so I had to rewrite a lot of elements.
Do you plan to rebuild this lib to be used outside of laravel ?

**Comment by restoore** [comment]
hi,
i havent plan to work on this project for now.
sorry :(


2018-03-18 15:28 GMT+01:00 Cethy <notifications@github.com>:

**Comment by Cethy** [comment]
No worries, at least it works. ;)
